# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty


cache:
  apt: true

env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

addons:
    apt:
        sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5

language: cpp

compiler:
  - g++-5

before_script:
  - g++ --version
  - wget http://sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2 -O /tmp/sfml.tar.bz2
  - tar -xjvf /tmp/sfml.tar.bz2
  - sudo cp -r SFML-2.1/* /usr/
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1
  - mkdir build
  - cd build
  - export COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
  - cmake ..

script:
  - make
  - cd ../bin
  - ls -la
#  - ./Simple