# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

cache:
  apt: true

env:
  global:
    - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
    - SFML_ROOT=/sfml
    - LD_LIBRARY_PATH=/sfml/lib

addons:
    apt:
        sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libxcb-image0
            - libxcb-image0-dev

language: cpp

compiler:
  - g++-5

before_install:
  - pip install --user cpp-coveralls

before_script:
  - sudo mkdir ~/sfml_install
  - sudo wget https://raw.githubusercontent.com/xmaayy/SFMLinstall/master/SFMLins -O ~/sfml_install/script
  - sudo chmod +x ~/sfml_install/script && cd ~/sfml_install && sh ./script
#  - wget http://www.sfml-dev.org/files/SFML-2.4.0-linux-gcc-64-bit.tar.gz -O /tmp/sfml.tar.gz
#  - tar -xxvf /tmp/sfml.tar.gz
#  - sudo mkdir /sfml
#  - sudo cp -r SFML-2.4.0/* /sfml/
#  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1
  - mkdir build
  - cd build
  - export COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
  - cmake ..

script:
  - make && make check

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
