# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

cache:
  apt: true

env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

addons:
    apt:
        sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libsfml-dev

language: cpp

compiler:
  - g++-5

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - export COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
  - cmake ..

script:
  - ./configure --enable-gcov && make && make check

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
